# Generated by Django 4.0.3 on 2022-03-15 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='replying_to',
        ),
    ]
