# Generated by Django 4.0.3 on 2022-03-12 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220310_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='last_edited_on',
        ),
        migrations.AddField(
            model_name='blog',
            name='header_image',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='blog',
            name='title',
            field=models.TextField(default=None),
        ),
    ]
