# Generated by Django 4.0.3 on 2022-03-12 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_last_edited_on_blog_header_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='header_image',
            new_name='thumbnail',
        ),
    ]
